apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgA5H8cbl6VfcVwnulMkSGQQNU/Zoat9r0ccqJVJJyorvcdMv0utWHk6dGNnE0m6eD+YMk4qPhRxL4JkRISqyqzT1KBpFEXjOIVlSPTRjugAJCNEyHw1gvRZbLp97arNP7xUVbJ99SZC2m/yfUc/2p/VYaF94PBPBrzEIP8tYrW/6dz5bTrE1RWLpCFCFnRR85/cu/pZr9taJM9OBWTuAjFuBsn0/LMwOXRK2h0lOb+DOkZSTTd/TwqLWyjG4/2H2BSvtE3vJ4bxoODCO1MjTC0y6qlYD9Zh4aweai5ZHDYLkVMmNmUlf/0/Oi7nRp7jBOKgjAV1xMcZve6qH2zsBl1aiw0J5dNFt3GUCRylQgytB6thdEn7aj4i3osPbNeHHe466xxP6bSOlK3VbrkuwGcTt9KM0D3zSxfHXbAvYJnJxG/28pIVFyt5N1m9Mfh1e+KOrnCxuk4eoSdEtCftKdoKLSpZint7iU5A+eL2l6kG6yUkackFaZap2tkaTMY26FgLGn+Jg0xI387O8Cr9LTWv9IBpD3CGge/o+4PTA+Kv8Rp7MvvJJomsunv2vNHIj5SvK+3V9uCK96ELAdjAkltJMNN5DW5dmNeQOsRWK5ZQzUkRKXbk29HPhZ3SJxXeYZ1W68Fg2wyHzPbtefIeSV/6RcQ3foA+tvjsvOtD5R0ROqvDnJVJQV8as5lWvoDLDM+RvYB2wpVILw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

